version: 2
jobs:
  primeiro:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  segundo:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"

  terceiro:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "terceir"
workflows:
  version: 2
  primeiro_e_segundo:
    jobs:
      - segundo
      - primeiro:
          requires:
            - segundo
      - hold:
          type: approval
          requires:
            - primeiro
      - terceiro:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - dev
                - /user-.*/
          requires:
            - hold
