---
    - name: Build elasticsearch 
      shell: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
        echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
        sudo apt update
        sudo apt install -y elasticsearch
    - lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        state: present
        regexp: '^network.host:'
        line: "network.host: localhost"
    - name: Restart service elasticsearch
      service:
        name: elasticsearch 
        state: restarted
    - name: Enable service elasticsearch, and not touch the running state
      service:
        name: elasticsearch
        enabled: yes
